#!/usr/bin/env python3


import argparse
import matplotlib.pyplot as plt
import numpy
import pandas as pd


parser = argparse.ArgumentParser()
parser.add_argument('srcfile')

args = parser.parse_args()

a = pd.read_csv(args.srcfile, delimiter=",").values
#print(a)
plt.plot(a)
plt.show()
