/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(annotated_to_msg_f.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(1790edc7f8a6f8be220f6173bb6e2909)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/capture_tools/annotated_to_msg_f.h>
// pydoc.h is automatically generated in the build directory
#include <annotated_to_msg_f_pydoc.h>

void bind_annotated_to_msg_f(py::module& m)
{

    using annotated_to_msg_f    = ::gr::capture_tools::annotated_to_msg_f;


    py::class_<annotated_to_msg_f, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<annotated_to_msg_f>>(m, "annotated_to_msg_f", D(annotated_to_msg_f))

        .def(py::init(&annotated_to_msg_f::make),
           D(annotated_to_msg_f,make)
        )
        




        
        .def("set_sync_word",&annotated_to_msg_f::set_sync_word,       
            py::arg("s"),
            D(annotated_to_msg_f,set_sync_word)
        )


        
        .def("set_packet_length",&annotated_to_msg_f::set_packet_length,       
            py::arg("arg0"),
            D(annotated_to_msg_f,set_packet_length)
        )

        ;




}








