/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(msg_to_gfsk_c.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(3d6daca9597a9c993b2adea75659ae4f)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/capture_tools/msg_to_gfsk_c.h>
// pydoc.h is automatically generated in the build directory
#include <msg_to_gfsk_c_pydoc.h>

void bind_msg_to_gfsk_c(py::module& m)
{

    using msg_to_gfsk_c    = ::gr::capture_tools::msg_to_gfsk_c;


    py::class_<msg_to_gfsk_c, gr::block, gr::basic_block,
        std::shared_ptr<msg_to_gfsk_c>>(m, "msg_to_gfsk_c", D(msg_to_gfsk_c))

        .def(py::init(&msg_to_gfsk_c::make),
           py::arg("samples_per_symbol"),
           py::arg("sensitivity"),
           py::arg("bt"),
           D(msg_to_gfsk_c,make)
        )
        




        
        .def("set_fixed_delay",&msg_to_gfsk_c::set_fixed_delay,       
            py::arg("arg0"),
            D(msg_to_gfsk_c,set_fixed_delay)
        )


        
        .def("set_fixed_delay_range",&msg_to_gfsk_c::set_fixed_delay_range,       
            py::arg("arg0"),
            D(msg_to_gfsk_c,set_fixed_delay_range)
        )


        
        .def("set_wait_settle",&msg_to_gfsk_c::set_wait_settle,       
            py::arg("arg0"),
            D(msg_to_gfsk_c,set_wait_settle)
        )


        
        .def("set_rampup_delay",&msg_to_gfsk_c::set_rampup_delay,       
            py::arg("arg0"),
            D(msg_to_gfsk_c,set_rampup_delay)
        )


        
        .def("set_rampdown_delay",&msg_to_gfsk_c::set_rampdown_delay,       
            py::arg("arg0"),
            D(msg_to_gfsk_c,set_rampdown_delay)
        )


        
        .def("set_max_queue_length",&msg_to_gfsk_c::set_max_queue_length,       
            py::arg("arg0"),
            D(msg_to_gfsk_c,set_max_queue_length)
        )


        
        .def("set_rampup_alpha",&msg_to_gfsk_c::set_rampup_alpha,       
            py::arg("arg0"),
            D(msg_to_gfsk_c,set_rampup_alpha)
        )


        
        .def("set_rampdown_alpha",&msg_to_gfsk_c::set_rampdown_alpha,       
            py::arg("arg0"),
            D(msg_to_gfsk_c,set_rampdown_alpha)
        )


        
        .def("set_value_between",&msg_to_gfsk_c::set_value_between,       
            py::arg("arg0"),
            D(msg_to_gfsk_c,set_value_between)
        )


        
        .def("set_reset_phase",&msg_to_gfsk_c::set_reset_phase,       
            py::arg("arg0"),
            D(msg_to_gfsk_c,set_reset_phase)
        )


        
        .def("set_repeat_packet",&msg_to_gfsk_c::set_repeat_packet,       
            py::arg("arg0"),
            D(msg_to_gfsk_c,set_repeat_packet)
        )


        
        .def("set_level_off",&msg_to_gfsk_c::set_level_off,       
            py::arg("arg0"),
            D(msg_to_gfsk_c,set_level_off)
        )


        
        .def("set_sensitivity",&msg_to_gfsk_c::set_sensitivity,       
            py::arg("arg0"),
            D(msg_to_gfsk_c,set_sensitivity)
        )


        
        .def("set_bt",&msg_to_gfsk_c::set_bt,       
            py::arg("arg0"),
            D(msg_to_gfsk_c,set_bt)
        )


        
        .def("set_randomize_phase",&msg_to_gfsk_c::set_randomize_phase,       
            py::arg("arg0"),
            D(msg_to_gfsk_c,set_randomize_phase)
        )


        
        .def("set_sensitivity_range",&msg_to_gfsk_c::set_sensitivity_range,       
            py::arg("arg0"),
            D(msg_to_gfsk_c,set_sensitivity_range)
        )


        
        .def("set_search_tag",&msg_to_gfsk_c::set_search_tag,       
            py::arg("arg0"),
            D(msg_to_gfsk_c,set_search_tag)
        )

        ;




}








