INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_CAPTURE_TOOLS capture_tools)

FIND_PATH(
    CAPTURE_TOOLS_INCLUDE_DIRS
    NAMES capture_tools/api.h
    HINTS $ENV{CAPTURE_TOOLS_DIR}/include
        ${PC_CAPTURE_TOOLS_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    CAPTURE_TOOLS_LIBRARIES
    NAMES gnuradio-capture_tools
    HINTS $ENV{CAPTURE_TOOLS_DIR}/lib
        ${PC_CAPTURE_TOOLS_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(CAPTURE_TOOLS DEFAULT_MSG CAPTURE_TOOLS_LIBRARIES CAPTURE_TOOLS_INCLUDE_DIRS)
MARK_AS_ADVANCED(CAPTURE_TOOLS_LIBRARIES CAPTURE_TOOLS_INCLUDE_DIRS)

